const MOCK_APPEALS = [
    {
        id: "APP-1029",
        username: "u/tech_enthusiast99",
        subreddit: "r/technology",
        accountAge: "4 years",
        karma: 12500,
        riskScore: "Low",
        toxicityScore: 12,
        spamScore: 5,
        sincerityScore: 89,
        manipulationScore: 15,
        status: "Pending",
        aiConfidence: 94,
        recommendedAction: "Approve",
        date: "2023-10-24T14:30:00Z",
        appealText: "I was banned for a rule 3 violation but I believe my post about the new quantum processor was actually compliant. I've been a contributing member for 4 years and never had an issue. The link I shared was from a peer-reviewed journal, not a blog.",
        previousHistory: "Clean",
        removedPosts: 0,
        warnings: 0
    },
    {
        id: "APP-1030",
        username: "u/crypto_bro_2024",
        subreddit: "r/technology",
        accountAge: "2 months",
        karma: 45,
        riskScore: "High",
        toxicityScore: 85,
        spamScore: 92,
        sincerityScore: 12,
        manipulationScore: 78,
        status: "Pending",
        aiConfidence: 98,
        recommendedAction: "Reject",
        date: "2023-10-24T15:45:00Z",
        appealText: "unban me now u guys r crazy my coin is legit and u banned me for spam?? it's not spam its the future. mod team is corrupt",
        previousHistory: "Multiple spam removals",
        removedPosts: 14,
        warnings: 3
    },
    {
        id: "APP-1031",
        username: "u/science_teacher_88",
        subreddit: "r/science",
        accountAge: "2 years",
        karma: 3400,
        riskScore: "Medium",
        toxicityScore: 24,
        spamScore: 10,
        sincerityScore: 65,
        manipulationScore: 30,
        status: "Pending",
        aiConfidence: 76,
        recommendedAction: "Ask Clarification",
        date: "2023-10-24T16:20:00Z",
        appealText: "Hello, my comment regarding the recent study on atmospheric carbon was removed and resulted in a temp ban. I linked my own published paper as a source. I understand self-promotion is limited, but it was directly relevant to the discussion.",
        previousHistory: "One prior warning",
        removedPosts: 1,
        warnings: 1
    },
    {
        id: "APP-1032",
        username: "u/troll_account_9000",
        subreddit: "r/worldnews",
        accountAge: "5 days",
        karma: -45,
        riskScore: "Toxic",
        toxicityScore: 95,
        spamScore: 40,
        sincerityScore: 5,
        manipulationScore: 85,
        status: "Pending",
        aiConfidence: 99,
        recommendedAction: "Reject & Mute",
        date: "2023-10-24T17:10:00Z",
        appealText: "Whatever, this sub is garbage anyway. Unban me so I can tell everyone how stupid the mods are.",
        previousHistory: "Ban evasion suspected",
        removedPosts: 5,
        warnings: 0
    }
];

const STATS = {
    totalAppeals: 1284,
    pending: 342,
    approvedRate: 64,
    toxicRate: 18
};
